version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_server
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: guest 
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - uala_net

  redis:
    image: redis:latest
    container_name: my-redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl
    networks:
      - uala_net
    healthcheck:
      test: ["CMD", "redis-cli", "-u", "redis://guest:guest@127.0.0.1:6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  postgres_db:
    image: postgres:latest
    container_name: mi_postgres_db
    environment:
      POSTGRES_USER: usrtweeter
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tweeter
    networks:
      - uala_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  uala_net:
    driver: bridge